version: '3'

services:
  salut-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: salutb
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data2

  salut-backend:
    image: salut-backend
    depends_on:
      - salut-postgres
    environment:
      # Убедитесь, что ваше приложение использует следующий хост для подключения к БД:
      DATABASE_HOST: salut-postgres
    ports:
      - "8080:8080"

volumes:
  pgdata: